#!/bin/bash
if test -d $1
then
	echo "El directorio $1 existe."
	numfi=`ls -p $1| grep -v / | wc -l`
	numfip=`ls -p $1/.. | grep -v / | wc -l`
	echo "El número de ficheros del directorio actual es: $numfi"
	echo "El número de ficheros del directorio $dan es: $numfip"
	if test $numfi -eq $numfip
	then
		echo "Coincide el número de ficheros de ambos directorios"
	else
		echo "No coincide el número de ficheros de ambos directorios"
	fi
else
	echo "El directorio $1 no ha sido encontrado."
fi
echo "Fin del shell cuenta-dir2"

