#!/bin/bash
read -p "Introducce un número: " n1
read -p "Introducce un segundo número: " n2
read -p "Intreoducce un tercer número: " n3
if test "$n1" -gt "$n2" -a "$n1" -gt "$n3" -a "$n2" -gt "$n3"
then
	echo "El mayor es $n1, el intermedio es el $n2 y el menor es $n3"
fi
if test "$n1" -gt "$n2" -a "$n1" -gt "$n3" -a "$n3" -gt "$n2"
then
	echo "El mayor es $n1, el intermedio es el $n3 y el menor es $n2"
fi
if test "$n2" -gt "$n1" -a "$n2" -gt "$n3" -a "$n1" -gt "$n3"
then
	echo "El mayor es $n2, el intermedio es el $n1 y el menor es $n3"
fi
if test "$n2" -gt "$n1" -a "$n2" -gt "$n3" -a "$n3" -gt "$n1"
then
	echo "El mayor es $n2, el intermedio es el $n3 y el menor es $n1"
fi
if test "$n3" -gt "$n1" -a "$n3" -gt "$n2" -a "$n2" -gt "$n1"
then
	echo "El mayor es $n3, el intermedio es el $n2 y el menor es $n1"
fi
if test "$n3" -gt "$n1" -a "$n3" -gt "$n2" -a "$n1" -gt "$n2"
then
	echo "El mayor es $n3, el intermedio es el $n1 y el menor es $n2"
fi
echo "Fin del shell may-men-inter"
