#!/bin/bash
read -p "Introducce un número positivo del 1 al 10: " n1
if test "$n1" -gt "1" -o "$n1" -lt "10"
then
	read -p "Introducce un segundo número positivo del 1 al 10: " n2
	if test "$n2" -gt "1" -o "$n2" -lt "10"
	then
		let resultado=$n1+$n2
		echo "El resultado de la suma de ambos números es: $resultado"
	else
		echo "Segundo número introduccio incorrecto"
		read -p "Introducce un segundo número positivo del 1 al 10: " n2
	fi
else
	echo "Primer número introduccido incorrecto"
	read -p "Introducce un número positivo del 1 al 10: " n1
fi
echo "Fin del shell suma-positivos"
