#!/bin/bash
echo "1.Número factorial"
echo "2.Aritmética"
echo "3.Tabla de multiplicar"
echo
read -p "Selecciona una opción: " opc
case $opc in
	1)bash ../adiccionales2020/factorial;;
	2)bash ../5-case/aritmetica;;
	3)bash ../adiccionales2020/tabla_multiplicar;;
	*)echo "Debe de introducir un número del 1 al 3.";;
esac
echo
echo "Fin del shell calculos"
